org: cadenmidkiff
app: nba-player-comparer
service: nba-player-tweeter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  stage: prod
  timeout: 15
  region: us-west-2

functions:
  TweetAction:
    handler: handler.TweetAction

    events:
      - schedule: rate(5 hours)
