service: nba-player-tweeter
frameworkVersion: '3'

#useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: prod
  timeout: 15
  region: us-west-2

functions:
  TweetAction:
    handler: handler.TweetAction

    events:
      - schedule: rate(5 hours)
    #      - cloudwatchLog: '/aws/lambda/hello'
    #      - cognitoUserPool:
    #          pool: MyUserPool
    #          trigger: PreSignUp
    #      - alb:
    #          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
    #          priority: 1
    #          conditions:
    #            host: example.com
    #            path: /hello

    #    Define function environment variables here
